export const countries = [
  {
     "name":"USA",
     "code":"USA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/us.png"
  },
  {
     "name":"Italy",
     "code":"ITA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/it.png"
  },
  {
     "name":"Spain",
     "code":"ESP",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/es.png"
  },
  {
     "name":"Germany",
     "code":"DEU",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/de.png"
  },
  {
     "name":"France",
     "code":"FRA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/fr.png"
  },
  {
     "name":"Iran",
     "code":"IRN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ir.png"
  },
  {
     "name":"UK",
     "code":"GBR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gb.png"
  },
  {
     "name":"Turkey",
     "code":"TUR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/tr.png"
  },
  {
     "name":"Switzerland",
     "code":"CHE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ch.png"
  },
  {
     "name":"Belgium",
     "code":"BEL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/be.png"
  },
  {
     "name":"Netherlands",
     "code":"NLD",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/nl.png"
  },
  {
     "name":"Canada",
     "code":"CAN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ca.png"
  },
  {
     "name":"Austria",
     "code":"AUT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/at.png"
  },
  {
     "name":"S. Korea",
     "code":"KOR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/kr.png"
  },
  {
     "name":"Portugal",
     "code":"PRT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/pt.png"
  },
  {
     "name":"Brazil",
     "code":"BRA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/br.png"
  },
  {
     "name":"Israel",
     "code":"ISR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/il.png"
  },
  {
     "name":"Sweden",
     "code":"SWE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/se.png"
  },
  {
     "name":"Norway",
     "code":"NOR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/no.png"
  },
  {
     "name":"Australia",
     "code":"AUS",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/au.png"
  },
  {
     "name":"Ireland",
     "code":"IRL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ie.png"
  },
  {
     "name":"Russia",
     "code":"RUS",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ru.png"
  },
  {
     "name":"Czechia",
     "code":"CZE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cz.png"
  },
  {
     "name":"Denmark",
     "code":"DNK",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/dk.png"
  },
  {
     "name":"Chile",
     "code":"CHL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cl.png"
  },
  {
     "name":"Ecuador",
     "code":"ECU",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ec.png"
  },
  {
     "name":"Malaysia",
     "code":"MYS",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/my.png"
  },
  {
     "name":"Poland",
     "code":"POL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/pl.png"
  },
  {
     "name":"Romania",
     "code":"ROU",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ro.png"
  },
  {
     "name":"Philippines",
     "code":"PHL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ph.png"
  },
  {
     "name":"Pakistan",
     "code":"PAK",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/pk.png"
  },
  {
     "name":"Japan",
     "code":"JPN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/jp.png"
  },
  {
     "name":"Luxembourg",
     "code":"LUX",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/lu.png"
  },
  {
     "name":"India",
     "code":"IND",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/in.png"
  },
  {
     "name":"Saudi Arabia",
     "code":"SAU",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sa.png"
  },
  {
     "name":"Indonesia",
     "code":"IDN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/id.png"
  },
  {
     "name":"Thailand",
     "code":"THA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/th.png"
  },
  {
     "name":"Finland",
     "code":"FIN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/fi.png"
  },
  {
     "name":"Greece",
     "code":"GRC",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gr.png"
  },
  {
     "name":"Peru",
     "code":"PER",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/pe.png"
  },
  {
     "name":"Mexico",
     "code":"MEX",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mx.png"
  },
  {
     "name":"South Africa",
     "code":"ZAF",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/za.png"
  },
  {
     "name":"Dominican Republic",
     "code":"DOM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/do.png"
  },
  {
     "name":"Serbia",
     "code":"SRB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/rs.png"
  },
  {
     "name":"Panama",
     "code":"PAN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/pa.png"
  },
  {
     "name":"Iceland",
     "code":"ISL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/is.png"
  },
  {
     "name":"Argentina",
     "code":"ARG",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ar.png"
  },
  {
     "name":"UAE",
     "code":"ARE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ae.png"
  },
  {
     "name":"Algeria",
     "code":"DZA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/dz.png"
  },
  {
     "name":"Colombia",
     "code":"COL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/co.png"
  },
  {
     "name":"Singapore",
     "code":"SGP",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sg.png"
  },
  {
     "name":"Croatia",
     "code":"HRV",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/hr.png"
  },
  {
     "name":"Qatar",
     "code":"QAT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/qa.png"
  },
  {
     "name":"Ukraine",
     "code":"UKR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ua.png"
  },
  {
     "name":"Egypt",
     "code":"EGY",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/eg.png"
  },
  {
     "name":"Estonia",
     "code":"EST",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ee.png"
  },
  {
     "name":"Slovenia",
     "code":"SVN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/si.png"
  },
  {
     "name":"New Zealand",
     "code":"NZL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/nz.png"
  },
  {
     "name":"Hong Kong",
     "code":"HKG",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/hk.png"
  },
  {
     "name":"Iraq",
     "code":"IRQ",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/iq.png"
  },
  {
     "name":"Morocco",
     "code":"MAR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ma.png"
  },
  {
     "name":"Armenia",
     "code":"ARM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/am.png"
  },
  {
     "name":"Diamond Princess",
     "code":"#Diamond_Princess",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/unknow.png"
  },
  {
     "name":"Lithuania",
     "code":"LTU",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/lt.png"
  },
  {
     "name":"Bahrain",
     "code":"BHR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bh.png"
  },
  {
     "name":"Hungary",
     "code":"HUN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/hu.png"
  },
  {
     "name":"Moldova, Republic of",
     "code":"MDA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/md.png"
  },
  {
     "name":"Bosnia",
     "code":"BIH",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ba.png"
  },
  {
     "name":"Cameroon",
     "code":"CMR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cm.png"
  },
  {
     "name":"Lebanon",
     "code":"LBN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/lb.png"
  },
  {
     "name":"Tunisia",
     "code":"TUN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/tn.png"
  },
  {
     "name":"Latvia",
     "code":"LVA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/lv.png"
  },
  {
     "name":"Bulgaria",
     "code":"BGR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bg.png"
  },
  {
     "name":"Kazakhstan",
     "code":"KAZ",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/kz.png"
  },
  {
     "name":"Slovakia",
     "code":"SVK",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sk.png"
  },
  {
     "name":"Azerbaijan",
     "code":"AZE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/az.png"
  },
  {
     "name":"Andorra",
     "code":"AND",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ad.png"
  },
  {
     "name":"Macedonia",
     "code":"MKD",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mk.png"
  },
  {
     "name":"Kuwait",
     "code":"KWT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/kw.png"
  },
  {
     "name":"Costa Rica",
     "code":"CRI",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cr.png"
  },
  {
     "name":"Cyprus",
     "code":"CYP",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cy.png"
  },
  {
     "name":"Uruguay",
     "code":"URY",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/uy.png"
  },
  {
     "name":"Belarus",
     "code":"BLR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/by.png"
  },
  {
     "name":"Taiwan",
     "code":"TWN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/tw.png"
  },
  {
     "name":"Réunion",
     "code":"REU",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/re.png"
  },
  {
     "name":"Jordan",
     "code":"JOR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/jo.png"
  },
  {
     "name":"Albania",
     "code":"ALB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/al.png"
  },
  {
     "name":"Burkina Faso",
     "code":"BFA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bf.png"
  },
  {
     "name":"Afghanistan",
     "code":"AFG",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/af.png"
  },
  {
     "name":"Cuba",
     "code":"CUB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cu.png"
  },
  {
     "name":"Oman",
     "code":"OMN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/om.png"
  },
  {
     "name":"San Marino",
     "code":"SMR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sm.png"
  },
  {
     "name":"Vietnam",
     "code":"VNM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/vn.png"
  },
  {
     "name":"Channel Islands",
     "code":"JEY",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/je.png"
  },
  {
     "name":"Uzbekistan",
     "code":"UZB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/uz.png"
  },
  {
     "name":"Honduras",
     "code":"HND",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/hn.png"
  },
  {
     "name":"Côte d'Ivoire",
     "code":"CIV",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ci.png"
  },
  {
     "name":"Senegal",
     "code":"SEN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sn.png"
  },
  {
     "name":"Ghana",
     "code":"GHA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gh.png"
  },
  {
     "name":"Malta",
     "code":"MLT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mt.png"
  },
  {
     "name":"Palestinian Territory, Occupied",
     "code":"PSE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ps.png"
  },
  {
     "name":"Nigeria",
     "code":"NGA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ng.png"
  },
  {
     "name":"Mauritius",
     "code":"MUS",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mu.png"
  },
  {
     "name":"Faroe Islands",
     "code":"FRO",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/fo.png"
  },
  {
     "name":"Montenegro",
     "code":"MNE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/me.png"
  },
  {
     "name":"Sri Lanka",
     "code":"LKA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/lk.png"
  },
  {
     "name":"Georgia",
     "code":"GEO",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ge.png"
  },
  {
     "name":"Venezuela",
     "code":"VEN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ve.png"
  },
  {
     "name":"Martinique",
     "code":"MTQ",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mq.png"
  },
  {
     "name":"DRC",
     "code":"COD",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cd.png"
  },
  {
     "name":"Brunei",
     "code":"BRN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bn.png"
  },
  {
     "name":"Bolivia",
     "code":"BOL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bo.png"
  },
  {
     "name":"Guadeloupe",
     "code":"GLP",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gp.png"
  },
  {
     "name":"Kyrgyzstan",
     "code":"KGZ",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/kg.png"
  },
  {
     "name":"Mayotte",
     "code":"MYT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/yt.png"
  },
  {
     "name":"Kenya",
     "code":"KEN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ke.png"
  },
  {
     "name":"Isle of Man",
     "code":"IMN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/im.png"
  },
  {
     "name":"Cambodia",
     "code":"KHM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/kh.png"
  },
  {
     "name":"Niger",
     "code":"NER",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ne.png"
  },
  {
     "name":"Trinidad and Tobago",
     "code":"TTO",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/tt.png"
  },
  {
     "name":"Gibraltar",
     "code":"GIB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gi.png"
  },
  {
     "name":"Paraguay",
     "code":"PRY",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/py.png"
  },
  {
     "name":"Rwanda",
     "code":"RWA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/rw.png"
  },
  {
     "name":"Liechtenstein",
     "code":"LIE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/li.png"
  },
  {
     "name":"Guinea",
     "code":"GIN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gn.png"
  },
  {
     "name":"Madagascar",
     "code":"MDG",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mg.png"
  },
  {
     "name":"Monaco",
     "code":"MCO",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mc.png"
  },
  {
     "name":"Aruba",
     "code":"ABW",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/aw.png"
  },
  {
     "name":"Bangladesh",
     "code":"BGD",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bd.png"
  },
  {
     "name":"French Guiana",
     "code":"GUF",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gf.png"
  },
  {
     "name":"Barbados",
     "code":"BRB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bb.png"
  },
  {
     "name":"Guatemala",
     "code":"GTM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gt.png"
  },
  {
     "name":"Djibouti",
     "code":"DJI",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/dj.png"
  },
  {
     "name":"Uganda",
     "code":"UGA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ug.png"
  },
  {
     "name":"Jamaica",
     "code":"JAM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/jm.png"
  },
  {
     "name":"El Salvador",
     "code":"SLV",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sv.png"
  },
  {
     "name":"Macao",
     "code":"MAC",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mo.png"
  },
  {
     "name":"Togo",
     "code":"TGO",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/tg.png"
  },
  {
     "name":"Mali",
     "code":"MLI",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ml.png"
  },
  {
     "name":"Zambia",
     "code":"ZMB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/zm.png"
  },
  {
     "name":"French Polynesia",
     "code":"PYF",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/pf.png"
  },
  {
     "name":"Bermuda",
     "code":"BMU",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bm.png"
  },
  {
     "name":"Ethiopia",
     "code":"ETH",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/et.png"
  },
  {
     "name":"Cayman Islands",
     "code":"CYM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ky.png"
  },
  {
     "name":"Bahamas",
     "code":"BHS",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bs.png"
  },
  {
     "name":"Guyana",
     "code":"GUY",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gy.png"
  },
  {
     "name":"Sint Maarten",
     "code":"SXM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sx.png"
  },
  {
     "name":"Congo",
     "code":"COG",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cg.png"
  },
  {
     "name":"Saint Martin",
     "code":"MAF",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mf.png"
  },
  {
     "name":"Eritrea",
     "code":"ERI",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/er.png"
  },
  {
     "name":"Gabon",
     "code":"GAB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ga.png"
  },
  {
     "name":"Myanmar",
     "code":"MMR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mm.png"
  },
  {
     "name":"Tanzania, United Republic of",
     "code":"TZA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/tz.png"
  },
  {
     "name":"Maldives",
     "code":"MDV",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mv.png"
  },
  {
     "name":"Haiti",
     "code":"HTI",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ht.png"
  },
  {
     "name":"New Caledonia",
     "code":"NCL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/nc.png"
  },
  {
     "name":"Syrian Arab Republic",
     "code":"SYR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sy.png"
  },
  {
     "name":"Benin",
     "code":"BEN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bj.png"
  },
  {
     "name":"Equatorial Guinea",
     "code":"GNQ",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gq.png"
  },
  {
     "name":"Mongolia",
     "code":"MNG",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mn.png"
  },
  {
     "name":"Namibia",
     "code":"NAM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/na.png"
  },
  {
     "name":"Saint Lucia",
     "code":"LCA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/lc.png"
  },
  {
     "name":"Dominica",
     "code":"DMA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/dm.png"
  },
  {
     "name":"Curaçao",
     "code":"CUW",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cw.png"
  },
  {
     "name":"Libyan Arab Jamahiriya",
     "code":"LBY",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ly.png"
  },
  {
     "name":"Sudan",
     "code":"SDN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sd.png"
  },
  {
     "name":"Suriname",
     "code":"SUR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sr.png"
  },
  {
     "name":"Greenland",
     "code":"GRL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gl.png"
  },
  {
     "name":"Grenada",
     "code":"GRD",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gd.png"
  },
  {
     "name":"Lao People's Democratic Republic",
     "code":"LAO",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/la.png"
  },
  {
     "name":"Mozambique",
     "code":"MOZ",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mz.png"
  },
  {
     "name":"Seychelles",
     "code":"SYC",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sc.png"
  },
  {
     "name":"MS Zaandam",
     "code":"#MS_Zaandam",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/unknow.png"
  },
  {
     "name":"Zimbabwe",
     "code":"ZWE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/zw.png"
  },
  {
     "name":"Antigua and Barbuda",
     "code":"ATG",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ag.png"
  },
  {
     "name":"Guinea-Bissau",
     "code":"GNB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gw.png"
  },
  {
     "name":"Saint Kitts and Nevis",
     "code":"KNA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/kn.png"
  },
  {
     "name":"Swaziland",
     "code":"SWZ",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sz.png"
  },
  {
     "name":"Angola",
     "code":"AGO",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ao.png"
  },
  {
     "name":"Central African Republic",
     "code":"CAF",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cf.png"
  },
  {
     "name":"Chad",
     "code":"TCD",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/td.png"
  },
  {
     "name":"Fiji",
     "code":"FJI",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/fj.png"
  },
  {
     "name":"Holy See (Vatican City State)",
     "code":"VAT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/va.png"
  },
  {
     "name":"Liberia",
     "code":"LBR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/lr.png"
  },
  {
     "name":"Somalia",
     "code":"SOM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/so.png"
  },
  {
     "name":"Cabo Verde",
     "code":"CPV",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cv.png"
  },
  {
     "name":"Mauritania",
     "code":"MRT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mr.png"
  },
  {
     "name":"Nepal",
     "code":"NPL",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/np.png"
  },
  {
     "name":"St. Barth",
     "code":"BLM",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bl.png"
  },
  {
     "name":"Nicaragua",
     "code":"NIC",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ni.png"
  },
  {
     "name":"Bhutan",
     "code":"BTN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bt.png"
  },
  {
     "name":"Montserrat",
     "code":"MSR",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ms.png"
  },
  {
     "name":"Turks and Caicos Islands",
     "code":"TCA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/tc.png"
  },
  {
     "name":"Botswana",
     "code":"BWA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bw.png"
  },
  {
     "name":"Gambia",
     "code":"GMB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/gm.png"
  },
  {
     "name":"Belize",
     "code":"BLZ",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bz.png"
  },
  {
     "name":"Anguilla",
     "code":"AIA",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/ai.png"
  },
  {
     "name":"British Virgin Islands",
     "code":"VGB",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/vg.png"
  },
  {
     "name":"Burundi",
     "code":"BDI",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bi.png"
  },
  {
     "name":"Malawi",
     "code":"MWI",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/mw.png"
  },
  {
     "name":"Saint Vincent and the Grenadines",
     "code":"VCT",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/vc.png"
  },
  {
     "name":"Caribbean Netherlands",
     "code":"BES",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/bq.png"
  },
  {
     "name":"Sierra Leone",
     "code":"SLE",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/sl.png"
  },
  {
     "name":"Papua New Guinea",
     "code":"PNG",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/pg.png"
  },
  {
     "name":"Timor-Leste",
     "code":"TLS",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/tl.png"
  },
  {
     "name":"China",
     "code":"CHN",
     "flag":"https://raw.githubusercontent.com/NovelCOVID/API/master/assets/flags/cn.png"
  }
];